import Head from "next/head";
import { useEffect, useState } from "react";
import { Inter } from "@next/font/google";
import Link from "next/link";
import { signOut, getSession } from "next-auth/react";
import { User, Guest } from "@/components";
import { ExpenseService } from "@/services";

const inter = Inter({ subsets: ["latin"] });

export default function Home({ session }) {

  function handleSignOut() {
    signOut();
  }

  return (
    <>
      <Head>
        <title>moingo</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      {session ? (
        <User
          session={session}
          handleSignOut={handleSignOut}
        />
      ) : (
        <Guest />
      )}
    </>
  );
}

export const getServerSideProps = async ({ req }) => {
  const session = await getSession({ req });

  return {
    props: {
      session,
    },
  };
};
